In [1]:
#kütüphaneler

import sqlite3
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd 
#veri ön işleme

veriler = pd.read_csv('veriler.csv')#veri yükleme
#print(veriler)



#encoder-> nominal veya ordinal ->numeric değerlere dönüş
ulke=veriler.iloc[:,0:1].values#sadece ülkelerin olduğu kolonu alıcak
print(ulke)#ülkeleri bastır

from sklearn import preprocessing 
le=preprocessing.LabelEncoder()#encoder

ulke[:,0]=le.fit_transform(veriler.iloc[:,0])#iloc integer a çevirdi ülkeleri
print(ulke)

ohe=preprocessing.OneHotEncoder()#encoder kolon başlıklarına etiketleri taşır 1 veya 0 olarak nitelendirir 
ulke=ohe.fit_transform(ulke).toarray()
print(ulke)




#encoder-> nominal veya ordinal ->numeric değerlere dönüş
c=veriler.iloc[:,-1:].values#sadece cinsiyet olduğu kolonu alıcak
print(c)#cinsiyet bastır

from sklearn import preprocessing 
le=preprocessing.LabelEncoder()#encoder

c[:,-1]=le.fit_transform(veriler.iloc[:,-1])#iloc integer a çevirdi cinsiyeti
print(c)

ohe=preprocessing.OneHotEncoder()#encoder kolon başlıklarına etiketleri taşır 1 veya 0 olarak nitelendirir 
c=ohe.fit_transform(c).toarray()
print(c)







Yas=veriler.iloc[:,1:4].values#1,2,3 kolonlarının bütün satırlarını bas  kolonlar=0,1,2,3,4


# numpy dizileri dataframe dönüşümü
sonuc=pd.DataFrame(data=ulke, index=range(22), columns=['fr','tr','us'])
print(sonuc)

sonuc2=pd.DataFrame(data=Yas, index=range(22), columns=['boy','kilo','yas'])
print(sonuc2)

cinsiyet=veriler.iloc[:,-1].values
print(cinsiyet)

sonuc3=pd.DataFrame(data=c[:,:1],index=range(22), columns=['cinsiyet'])#veriyi c den alıp sadece erkek olup olmamasını 1,0 şeklinde vericek
print(sonuc3)

#dataframeleri birleştirmek, concat işlemi dikey boyutta yapılır
s= pd.concat([sonuc,sonuc2],axis=1)#boy kilo yaş ülke data frame i
print(s)

s2=pd.concat([s,sonuc3],axis=1)#boy kilo yaş ülke cinsiyet data frame i
print(s2)

#verileri bölmek
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(s,sonuc3,test_size=0.33,random_state=0)

#öznitelik ölçekleme
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_train,y_train)#x_trainden y_traini öğren
#verinin % 67 lık kısmıyla öğrendik,şimdi %33 kalan kısımla yani x_test ile tahmin edelim
y_pred=regressor.predict(x_test)

boy=s2.iloc[:,3:4].values#boy kolonunu ayırıcaz bağımlı değişkeni içerir
print(boy)
sol=s2.iloc[:,:3]
sag=s2.iloc[:,4:]

veri=pd.concat([sol,sag],axis=1)#concat birleştirme fonksiyonu, veri=bağımsız değişkenleri içerir

x_train,x_test,y_train,y_test=train_test_split(veri,boy,test_size=0.33,random_state=0)

r2=LinearRegression()
r2.fit(x_train,y_train)#x_trainden y_traini öğren
#verinin % 67 lık kısmıyla öğrendik,şimdi %33 kalan kısımla yani x_test ile tahmin edelim
y_pred=r2.predict(x_test)


# p value bulmaya çalışalım
import statsmodels.api as sm
#ones 22 satır 1 kolondan oluşan 1 lerin olduğu matris oluşturur
X=np.append(arr=np.ones((22,1)).astype(int),values=veri,axis=1)#22 satır 1 kolondan oluşan integer tipinde bir arrayi veri dizisine ekle

X_l=veri.iloc[:,[0,1,2,3,4,5]].values
X_l=np.array(X_l,dtype=float)
model=sm.OLS(boy,X_l).fit()
print(model.summary())

X_l=veri.iloc[:,[0,1,2,3,5]].values
X_l=np.array(X_l,dtype=float)
model=sm.OLS(boy,X_l).fit()
print(model.summary())


X_l=veri.iloc[:,[0,1,2,3]].values
X_l=np.array(X_l,dtype=float)
model=sm.OLS(boy,X_l).fit()
print(model.summary())







[['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['us']
 ['us']
 ['us']
 ['us']
 ['us']
 ['us']
 ['fr']
 ['fr']
 ['fr']
 ['fr']
 ['fr']
 ['fr']
 ['fr']]
[[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
[['e']
 ['e']
 ['k']
 ['k']
 ['e']
 ['e']
 ['e']
 ['e']
 ['k']
 ['e']
 ['k']
 ['k']
 ['k']
 ['k']
 ['k']
 ['e']
 ['e']
 ['e']
 ['e']
 ['k']
 ['k']
 ['k']]
[[0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]]
[[1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 