In [1]:
#kütüphaneler

import sqlite3
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd 
#veri yükleme

veriler = pd.read_csv('eksikveriler.csv')
#print(veriler)

""""boy = veriler[{'boy'}]
print(boy)"""

"""boykilo=veriler[["boy","kilo"]]
print(boykilo)"""

class insan:
    boy=180
    def kosmak(self,b):
        return b+10
merve=insan()
print(merve.boy)
print(merve.kosmak(90))

#eksikveriler
#sci - kit learn 
from sklearn.impute import SimpleImputer

#ortalama değerleri(mean) nan değerler yerine yazıcak
imputer=SimpleImputer(missing_values=np.nan, strategy='mean')#obje oluşturuyoruz

Yas=veriler.iloc[:,1:4].values
print(Yas)

#fit fonksiyonu öğrenilecek olan değer,transform öğrendiğini uygulamaya yarar
imputer=imputer.fit(Yas[:,1:4])#yaşın 1den 4 e kadar olan kolonlarını öğrenmesini sağlıyoruz
Yas[:,1:4]=imputer.transform(Yas[:,1:4])#imputer öğrenme işini yapacak,yani ortalama değer
print(Yas)#28.45 ortalama artık non değer yerine geldi

ulke=veriler.iloc[:,0:1].values#sadece ülkelerin olduğu kolonu alıcak
print(ulke)#ülkeleri bastır

from sklearn import preprocessing 
le=preprocessing.LabelEncoder()
ulke[:,0]=le.fit_transform(veriler.iloc[:,0])#iloc integer a çevirdi ülkeleri
print(ulke)

ohe=preprocessing.OneHotEncoder()
ulke=ohe.fit_transform(ulke).toarray()
print(ulke)

print(list(range(22)))
sonuc=pd.DataFrame(data=ulke, index=range(22), columns=['fr','tr','us'])
print(sonuc)

sonuc2=pd.DataFrame(data=Yas, index=range(22), columns=['boy','kilo','yas'])
print(sonuc2)

cinsiyet=veriler.iloc[:,-1].values
print(cinsiyet)

sonuc3=pd.DataFrame(data=cinsiyet,index=range(22), columns=['cinsiyet'])
print(sonuc3)

#dataframeleri birleştirmek, concat işlemi dikey boyutta yapılır
s= pd.concat([sonuc,sonuc2],axis=1)#boy kilo yaş ülke data frame i
print(s)

s2=pd.concat([s,sonuc3],axis=1)#boy kilo yaş ülke cinsiyet data frame i
print(s2)

#verileri bölmek

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(s,sonuc,test_size=0.33,random_state=0)

180
100
[[130.  30.  10.]
 [125.  36.  11.]
 [135.  34.  10.]
 [133.  30.   9.]
 [129.  38.  12.]
 [180.  90.  30.]
 [190.  80.  25.]
 [175.  90.  35.]
 [177.  60.  22.]
 [185. 105.  33.]
 [165.  55.  27.]
 [155.  50.  44.]
 [160.  58.  nan]
 [162.  59.  41.]
 [167.  62.  55.]
 [174.  70.  47.]
 [193.  90.  nan]
 [187.  80.  27.]
 [183.  88.  28.]
 [159.  40.  29.]
 [164.  66.  32.]
 [166.  56.  42.]]
[[130.    30.    10.  ]
 [125.    36.    11.  ]
 [135.    34.    10.  ]
 [133.    30.     9.  ]
 [129.    38.    12.  ]
 [180.    90.    30.  ]
 [190.    80.    25.  ]
 [175.    90.    35.  ]
 [177.    60.    22.  ]
 [185.   105.    33.  ]
 [165.    55.    27.  ]
 [155.    50.    44.  ]
 [160.    58.    28.45]
 [162.    59.    41.  ]
 [167.    62.    55.  ]
 [174.    70.    47.  ]
 [193.    90.    28.45]
 [187.    80.    27.  ]
 [183.    88.    28.  ]
 [159.    40.    29.  ]
 [164.    66.    32.  ]
 [166.    56.    42.  ]]
[['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 [